#ifndef HAVE_CONFIG_H
#define HAVE_CONFIG_H

#cmakedefine HAVE_ACE_STACK_TRACE_H

#cmakedefine USE_MULTI_THREAD_MAP

#define VERSION "${MANGOS_VERSION}"

#define CLIENT_VERSION ${CLIENT_VERSION}

#endif /* HAVE_CONFIG_H */
