#ifndef MANGOS_CONFIG_H
#define MANGOS_CONFIG_H

#cmakedefine HAVE_ACE_STACK_TRACE_H

#cmakedefine USE_MULTI_THREAD_MAP

#define MANGOS_VERSION "${MANGOS_VERSION}"

#define CLIENT_VERSION ${CLIENT_VERSION}

#endif /* MANGOS_CONFIG_H */
